### ISSUE TITLE
Writing tests

### ISSUE THREAD

**Issue by Ic3n** [grumpydev/TinyMessenger#8]
Hi, we have an private async method in ViewModel that is called as callback of subscribe. 

However when I wrote integration tests asserts are called before message is processed. In normal scenario I'd await that method but can't do it when using Messages. 

Is there a nice way to write such test.

**Comment by ffyhlkain** [comment]
This is a very old question, but just in case someone comes here and wonders the same, here's a pseudo example code for a test method for testing async messages:

`public class TestEvent : TinyMessageBase`
`{`       
`        public string TestData { private set; get; }`
`        public TestEvent(object sender, string data) : base(sender) { TestData = data; }`
`}`


`...`
`var eventBus = new TinyMessengerHub();`
`var eventData = string.Empty;`
`eventBus.Subscribe<TestEvent>((evt) => { Console.Write("received test event. data: " + evt.TestData); eventData = evt.TestData; });`
`var testEvent = new TestEvent(this, "hello world");`
`eventBus.PublishAsync<TestEvent>(testEvent, (result) => { Assert.AreEqual(eventData, testEvent.TestData); });`

**Comment by Ic3n** [comment]
old indeed
